### ISSUE TITLE
Interested to appear on the https://faust.grame.fr/community/powered-by-faust/ page ?

### ISSUE THREAD

**Issue by sletz** [elaforge/karya#1]

**Comment by elaforge** [comment]
Sure, what would you need for that?  Looks like you'd need a little paragraph and possible picture?

**Comment by sletz** [comment]
Yes, exactly !

**Comment by elaforge** [comment]
Ok, here's a paragraph:

Karya is a score language editor with support for scales, instrumental techniques, and ornaments, with special support for Balinese, Javanese, and Carnatic music.  It has backends for MIDI, supercollider OSC, lilypond, and an incremental audio renderer that uses Faust or samples.  You can write instruments in Faust and integrate them into a score along with samples and MIDI instruments.  Due to incremental rendering, even computationally expensive instruments are not a problem.

Picture: https://ofb.net/~elaforge/karya/doc/data/img/screen/evvari.png

**Comment by sletz** [comment]
Done here: https://faust.grame.fr/community/powered-by-faust/#karya thanks !
